### ISSUE TITLE
Example Images and Ground Truth files 

### ISSUE THREAD

**Issue by apatil4** [sciencefictionlab/chargrid-pytorch#2]
First of all, thanks for providing this and it is really helpful.
I wanted to see if you can update the repository with some example data files i.e some images of the invoices or documents that you tested this on. Also, example ground truth files and classes so that we can get it running from ground up. It will be really helpful.

Below are the things that would be helpful. 

- Input images must be located in the folder dir_img = "./data/img_inputs/"
- Input bounding boxes (ground truth) must be located in the folder dir_boxes = "./data/gt_boxes/"
- Input classes (ground truth) must be located in the folder dir_classes = "./data/gt_classes/"

**Comment by rishabh-gupta-fk** [comment]
@apatil4 Are you able to do prediction using the trained model? Can you please share how to?

**Comment by pragati2112** [comment]
Hi @apatil4 here is the s3 url - s3://document-intelligence-dataset/icdar/
you can download the dataset which we are using.
Thanks!

**Comment by pragati2112** [comment]
Hi @apatil4 here is the s3 url - https://document-intelligence-dataset.s3.eu-central-1.amazonaws.com/icdar_690.7z
You can download the dataset from here.
Thanks!

**Comment by apatil4** [comment]
Thanks a lot @pragati2112
